name: CD

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Jekyll site CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Pull docker image
        run: sudo docker pull ggrenka/website-test:latest
      - name: Del old docker cont
        run: sudo docker rm -f website-test-container || true
      - name: Run Docker container
        run: sudo docker run -d --name website-test-container ggrenka/website-test
